spring:
  profiles:
    active: test

---
spring:
  profiles: test
  datasource:
    #driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lottery?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    #初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 6000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 6000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    logSlowSql: true
    # 通过connectProperties属性来打开mergeSql功能,慢SQL记录
    #connectionProperties:
      #druid.stat.mergeSql: false
      #druid.stat.slowSqlMillis: 5000
    validation-query: SELECT 1
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    #time-between-eviction-runs-millis: 30000
    #min-evictable-idle-time-millis: 10000
    connection-timeout: 31536000
  jpa:
    hibernate:
      ddl-auto: update
      auto-reconnect: true
    properties:
      javax.persistence.sharedCache.mode: ALL
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  swagger:
    enable: true
  messages:
    basename: i18n/message
    encoding: UTF-8
  dispatcherServletUrlPattern: "/service/*"
server:
  port: 19000
  #context-path: /api
  session-timeout: 100800
#thymeleaf start
spring.thymeleaf.mode: HTML5
spring.thymeleaf.encoding: UTF-8
spring.thymeleaf.content-type: text/html
#开发时关闭缓存,不然没法看到实时页面
spring.thymeleaf.cache: false
#thymeleaf end

